### ISSUE TITLE
crash with 'source gvp' in zsh

### ISSUE THREAD

**Issue by xuxiangyang** [pote/gvp#26] opened 2015-03-10 13:24 UTC
I use zsh， with oh-my-zsh config。It's ok to run as `gvp`、`source gvp in`、`source gvp out`。but crash with `source gvp`

I need some help，can you help me?

**Comment by pote** [comment] 2015-03-10 14:31
Wow, ok, I haven't used zsh yet, but let's see what we can do... what version of gvp are you running?

**Comment by xuxiangyang** [comment] 2015-03-11 02:24
I install gvp with brew。the version is v0.1.0

**Comment by pote** [comment] 2015-03-11 12:34
`v0.1.0` had a bug that made it crash when the `.godeps` directory doesn't exist, did you check that? run `gvp init` and try it again.

I'll push new stuff into homebrew soon, apologies for the version there being outdated!

**Comment by johntdyer** [comment] 2015-05-28 03:32
I think I am running into the same issue.  I have tried 0.2.0 and HEAD from github and every time I try `source gvp` the session just dies.

**Comment by siddharthist** [comment] 2015-07-07 16:21
I am having the same problem. v0.1.0 and zsh 5.0.8 (x86_64-unknown-linux-gnu).

**Comment by siddharthist** [comment] 2015-07-09 15:38
If it helps, here is the output of a little log
```
gvp/bin% zsh -c "source ./gvp" > log
gvp/bin% cat log
usage: gvp [COMMAND]

SYNOPSIS
    gvp stands for Go Versioning Packager and is based on [gst](http://github.com/tonchis/gst),
    a similar tool that provides vendoring functionality for Ruby gems.

    The tool modifies your GOPATH to point to a local .godeps/ directory so that you
    can keep the dependencies of your project isolated there, it also modifies
    GOBIN and PATH to include the new GOPATH/bin directory.
[...]
```
Also, I think this issue is fixed in master, can anybody confirm?

**Comment by siddharthist** [comment] 2015-07-09 21:21
So after some more examination, what I believe is happening is that the line `usage && exit 1` exits the shell rather than the script, because it is being sourced rather than ran, so the `exit` runs in zsh. This only happens when the case statement reads something like `case "${1}"`, instead of its current version.

**Comment by siddharthist** [comment] 2015-07-10 07:07
Confirmed: the error is caused by `exit 1`. It can be fixed by deleting that part of the line. 

Additionally, another case can be added, namely
```bash
"") ;&
"in")
    [...]
    ;;
```

**Closed** 2015-07-22 19:21 UTC
